# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uicontroller.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import webbrowser
import json
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import vgamepad as vg
def val_to_keys(stt = {}):
        invrt = {}
        for k,v in stt.items():
                if k == "running" or k == "obj" or k == "listening" or k == "key":
                        continue
                print(k,v)
                if invrt.get(v) is not None:
                        raise Exception(f"DUPLICATE {k} AND {invrt.get(v)}")
                else:
                        invrt[v] = k
        return invrt
numb_to_func = {
        1: vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB,
        2: vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
        3: vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,
        4: vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB,
        5: "LUP",
        6 : "LRIGHT",
        7 : "LDOWN",
        8 : "LLEFT",
        9 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
        10 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
        11 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
        12 : vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,
        13 : vg.XUSB_BUTTON.XUSB_GAMEPAD_X,
        14 : vg.XUSB_BUTTON.XUSB_GAMEPAD_Y,
        15 : vg.XUSB_BUTTON.XUSB_GAMEPAD_B,
        16 : vg.XUSB_BUTTON.XUSB_GAMEPAD_A,
        17 : "RUP",
        18 : "RRIGHT",
        19 : "RDOWN",
        20 : "RLEFT",
        21: vg.XUSB_BUTTON.XUSB_GAMEPAD_START,



}

kb_to_str = {
        "KEY.UP" : "UP_ARR",
        "KEY.RIGHT" : "R_ARR",
        "KEY.LEFT" : "L_ARR",
        "KEY.DOWN" : "D_ARR",
        "KEY.SPACE" : "SPACE",
        "KEY.DOWN" : "D_ARR",
        "KEY.DOWN" : "D_ARR",
        "KEY.NUM_LOCK" : "NUM_L",
        "KEY.NUM_LOCK" : "NUM_L",
}
func_to_num = val_to_keys(numb_to_func)
stt_glob = {}
to_change = {}
class CustomQedit(QtWidgets.QTextEdit):
        keyPressed = QtCore.pyqtSignal(object)
        change = QtCore.pyqtSignal(object, str, int)
        def __init__(self, cntl) -> None:
              
              super().__init__(cntl)
              
              self.keyPressed.connect(Ui_MainWindow.func)
        def mousePressEvent(self, event):
                
                if not stt_glob["listening"] and event.button() == QtCore.Qt.LeftButton: self.keyPressed.emit(self)
                else: super().mousePressEvent(event)

class GlobalButton(QtWidgets.QPushButton):
        start_stop = QtCore.pyqtSignal(int)
        def __init__(self, cntl, stt) -> None:
              super().__init__(cntl)
              self.stt = stt
        def stop(self, i):
                global to_change
                if self.stt["running"]:
                        self.stt["running"] = False
                        self.setText("START (F6)")
                        self.setStyleSheet("background-color: #00941b;\n"
                "border-color: #00941b;\n"
                "color: #fff;\n"
                "border-radius: 25px;\n"
                "\n"
"")
                else:
                        
                        try:
                                invrt = val_to_keys(to_change)
                        except Exception as err:   
                                Ui_MainWindow.make_msg(err = err)
                                return
                        tmp = {}
                        for k,v in invrt.items():
                                self.stt[k] = numb_to_func[v]
                                tmp[k] = numb_to_func[v]
                        with open('default.json', 'w') as convert_file:
                                convert_file.write(json.dumps(tmp))
                        
                        self.stt["running"] = True
                        self.setText("STOP (F6)")
                        self.setStyleSheet("background-color: #d9001d;\n"
        "border-color: #d9001d;\n"
        "color: #fff;\n"
        "border-radius: 25px;\n"
        "\n"
        "")

class Ui_MainWindow(object):
    
    
    def post_func(cstm: CustomQedit, key: str, id: int):
        cstm.change.disconnect()
        
        tmp = key
        if kb_to_str.get(tmp.upper()) is not None:
                tmp = kb_to_str[tmp.upper()]
        cstm.setHtml(f"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">{id}: </span><span style=\" font-size:10pt;\">{tmp.upper()}</span></p></body></html>")
        stt_glob["prev_key"] = ""
        to_change[id] = key

    
    def func(cstm: CustomQedit):
        
        if stt_glob["running"]:
                return
        stt_glob["listening"] = True
        stt_glob["obj"] = cstm
        
        ret = cstm.toPlainText()
        key = ret.split(":")[0]
        stt_glob["key"] = int(key)
        stt_glob["prev_key"] = ret.split(":")[1].strip()
        cstm.setHtml(f"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">{key}: </span><span style=\" font-size:10pt;\">...</span></p></body></html>")
        
        cstm.change.connect(Ui_MainWindow.post_func)
        print(ret)
    def make_msg(err = "?"):
        print(err)
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Critical)

        msg.setText("ERROR")
        msg.setInformativeText(str(err))
        msg.setWindowTitle("Incorrect Mapping")
        
        msg.setStandardButtons( QMessageBox.Close)
        msg.exec_()
	
    def setupUi(self, MainWindow, stt):
        global stt_glob
        
        stt_glob = stt
        self.stt = stt
        for k,v in self.stt.items():
                if k == "running" or k == "obj" or k == "listening" or k == "key" or k == "prev_key":
                        continue

                to_change[func_to_num[v]] = k
        try:
                self.invrt = val_to_keys(stt)
        except Exception as err:
                
               self.make_msg(err)
        
        MainWindow.setObjectName("NoControl")
        MainWindow.resize(1031, 720)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 761, 691))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./imgs/controller.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.LB = CustomQedit(self.centralwidget)
        self.LB.setGeometry(QtCore.QRect(250, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LB.setFont(font)

        
        self.LB.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LB.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LB.setReadOnly(True)
        self.LB.setObjectName("LB")
        self.LT = CustomQedit(self.centralwidget)
        self.LT.setGeometry(QtCore.QRect(270, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LT.setFont(font)
        self.LT.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LT.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LT.setReadOnly(True)
        self.LT.setObjectName("LT")
        self.RT = CustomQedit(self.centralwidget)
        self.RT.setGeometry(QtCore.QRect(860, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.RT.setFont(font)
        self.RT.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RT.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.RT.setReadOnly(True)
        self.RT.setObjectName("RT")
        self.RB = CustomQedit(self.centralwidget)
        self.RB.setGeometry(QtCore.QRect(870, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.RB.setFont(font)
        self.RB.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RB.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.RB.setReadOnly(True)
        self.RB.setObjectName("RB")
        self.LB_2 = CustomQedit(self.centralwidget)
        self.LB_2.setGeometry(QtCore.QRect(500, 490, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LB_2.setFont(font)
        self.LB_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LB_2.setAutoFillBackground(False)
        self.LB_2.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LB_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_2.setReadOnly(True)
        self.LB_2.setObjectName("LB_2")
        self.LB_3 = CustomQedit(self.centralwidget)
        self.LB_3.setGeometry(QtCore.QRect(510, 520, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LB_3.setFont(font)
        self.LB_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LB_3.setAutoFillBackground(False)
        self.LB_3.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LB_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_3.setReadOnly(True)
        self.LB_3.setObjectName("LB_3")
        self.LB_4 = CustomQedit(self.centralwidget)
        self.LB_4.setGeometry(QtCore.QRect(440, 560, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LB_4.setFont(font)
        self.LB_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LB_4.setAutoFillBackground(False)
        self.LB_4.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LB_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_4.setReadOnly(True)
        self.LB_4.setObjectName("LB_4")
        self.LB_5 = CustomQedit(self.centralwidget)
        self.LB_5.setGeometry(QtCore.QRect(540, 580, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LB_5.setFont(font)
        self.LB_5.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LB_5.setAutoFillBackground(False)
        self.LB_5.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LB_5.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_5.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LB_5.setReadOnly(True)
        self.LB_5.setObjectName("LB_5")
        self.RbmU = CustomQedit(self.centralwidget)
        self.RbmU.setGeometry(QtCore.QRect(410, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.RbmU.setFont(font)
        self.RbmU.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RbmU.setAutoFillBackground(False)
        self.RbmU.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.RbmU.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmU.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmU.setReadOnly(True)
        self.RbmU.setObjectName("RbmU")
        self.RbmR = CustomQedit(self.centralwidget)
        self.RbmR.setGeometry(QtCore.QRect(520, 240, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.RbmR.setFont(font)
        self.RbmR.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RbmR.setAutoFillBackground(False)
        self.RbmR.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.RbmR.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmR.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmR.setReadOnly(True)
        self.RbmR.setObjectName("RbmR")
        self.RbmL = CustomQedit(self.centralwidget)
        self.RbmL.setGeometry(QtCore.QRect(300, 320, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.RbmL.setFont(font)
        self.RbmL.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RbmL.setAutoFillBackground(False)
        self.RbmL.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.RbmL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmL.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmL.setReadOnly(True)
        self.RbmL.setObjectName("RbmL")
        self.RbmD = CustomQedit(self.centralwidget)
        self.RbmD.setGeometry(QtCore.QRect(270, 360, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.RbmD.setFont(font)
        self.RbmD.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RbmD.setAutoFillBackground(False)
        self.RbmD.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.RbmD.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmD.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmD.setReadOnly(True)
        self.RbmD.setObjectName("RbmD")
        self.LbmU = CustomQedit(self.centralwidget)
        self.LbmU.setGeometry(QtCore.QRect(870, 410, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LbmU.setFont(font)
        self.LbmU.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LbmU.setAutoFillBackground(False)
        self.LbmU.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LbmU.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmU.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmU.setReadOnly(True)
        self.LbmU.setObjectName("LbmU")
        self.LbmR = CustomQedit(self.centralwidget)
        self.LbmR.setGeometry(QtCore.QRect(870, 470, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LbmR.setFont(font)
        self.LbmR.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LbmR.setAutoFillBackground(False)
        self.LbmR.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LbmR.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmR.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmR.setReadOnly(True)
        self.LbmR.setObjectName("LbmR")
        self.Xk = CustomQedit(self.centralwidget)
        self.Xk.setGeometry(QtCore.QRect(630, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Xk.setFont(font)
        self.Xk.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Xk.setAutoFillBackground(False)
        self.Xk.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.Xk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Xk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Xk.setReadOnly(True)
        self.Xk.setObjectName("Xk")
        self.Yk = CustomQedit(self.centralwidget)
        self.Yk.setGeometry(QtCore.QRect(740, 220, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Yk.setFont(font)
        self.Yk.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Yk.setAutoFillBackground(False)
        self.Yk.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.Yk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Yk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Yk.setReadOnly(True)
        self.Yk.setObjectName("Yk")
        self.Bk = CustomQedit(self.centralwidget)
        self.Bk.setGeometry(QtCore.QRect(800, 260, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Bk.setFont(font)
        self.Bk.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Bk.setAutoFillBackground(False)
        self.Bk.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.Bk.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Bk.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Bk.setReadOnly(True)
        self.Bk.setObjectName("Bk")
        self.Ak = CustomQedit(self.centralwidget)
        self.Ak.setGeometry(QtCore.QRect(860, 310, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Ak.setFont(font)
        self.Ak.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ak.setAutoFillBackground(False)
        self.Ak.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.Ak.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Ak.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Ak.setReadOnly(True)
        self.Ak.setObjectName("Ak")
        self.LbmD = CustomQedit(self.centralwidget)
        self.LbmD.setGeometry(QtCore.QRect(850, 510, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LbmD.setFont(font)
        self.LbmD.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LbmD.setAutoFillBackground(False)
        self.LbmD.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LbmD.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmD.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmD.setReadOnly(True)
        self.LbmD.setObjectName("LbmD")
        self.LbmL = CustomQedit(self.centralwidget)
        self.LbmL.setGeometry(QtCore.QRect(840, 540, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.LbmL.setFont(font)
        self.LbmL.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LbmL.setAutoFillBackground(False)
        self.LbmL.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.LbmL.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmL.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LbmL.setReadOnly(True)
        self.LbmL.setObjectName("LbmL")
        self.pushButton = GlobalButton(self.centralwidget, stt)
        self.pushButton.start_stop.connect(lambda i: self.pushButton.stop(i))
        self.pushButton.clicked.connect(self.pushButton.stop)
        self.pushButton.setGeometry(QtCore.QRect(620, 640, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: #d9001d;\n"
"border-color: #d9001d;\n"
"color: #fff;\n"
"border-radius: 25px;\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.RbmU_2 = CustomQedit(self.centralwidget)
        self.RbmU_2.setGeometry(QtCore.QRect(580, 340, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.RbmU_2.setFont(font)
        self.RbmU_2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RbmU_2.setAutoFillBackground(False)
        self.RbmU_2.setStyleSheet("border: 1px solid #ced4da;\n"
"border-radius: 25px;")
        self.RbmU_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmU_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.RbmU_2.setReadOnly(True)
        self.RbmU_2.setObjectName("RbmU_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 40, 171, 16))
        self.line.setStyleSheet("")
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.txt1_2 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_2.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.txt1_2.setStyleSheet("")
        self.txt1_2.setObjectName("txt1_2")
        self.txt1_3 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_3.setGeometry(QtCore.QRect(10, 50, 151, 21))
        self.txt1_3.setStyleSheet("")
        self.txt1_3.setObjectName("txt1_3")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 70, 171, 16))
        self.line_2.setStyleSheet("")
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.txt1_4 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_4.setGeometry(QtCore.QRect(10, 80, 151, 21))
        self.txt1_4.setStyleSheet("")
        self.txt1_4.setObjectName("txt1_4")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 100, 171, 16))
        self.line_3.setStyleSheet("")
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.txt1_5 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_5.setGeometry(QtCore.QRect(10, 110, 171, 21))
        self.txt1_5.setStyleSheet("")
        self.txt1_5.setObjectName("txt1_5")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 130, 171, 16))
        self.line_4.setStyleSheet("")
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.txt1_6 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_6.setGeometry(QtCore.QRect(10, 140, 151, 21))
        self.txt1_6.setStyleSheet("")
        self.txt1_6.setObjectName("txt1_6")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 160, 171, 16))
        self.line_5.setStyleSheet("")
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.txt1_7 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_7.setGeometry(QtCore.QRect(10, 170, 161, 21))
        self.txt1_7.setStyleSheet("")
        self.txt1_7.setObjectName("txt1_7")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 190, 171, 16))
        self.line_6.setStyleSheet("")
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 250, 171, 16))
        self.line_7.setStyleSheet("")
        self.line_7.setLineWidth(3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.txt1_9 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_9.setGeometry(QtCore.QRect(10, 200, 151, 21))
        self.txt1_9.setStyleSheet("")
        self.txt1_9.setObjectName("txt1_9")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(10, 220, 171, 16))
        self.line_11.setStyleSheet("")
        self.line_11.setLineWidth(3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.txt1_11 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_11.setGeometry(QtCore.QRect(10, 230, 151, 21))
        self.txt1_11.setStyleSheet("")
        self.txt1_11.setObjectName("txt1_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(10, 280, 171, 16))
        self.line_12.setStyleSheet("")
        self.line_12.setLineWidth(3)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.txt1_12 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_12.setGeometry(QtCore.QRect(10, 260, 151, 21))
        self.txt1_12.setStyleSheet("")
        self.txt1_12.setObjectName("txt1_12")
        self.txt1_8 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_8.setGeometry(QtCore.QRect(10, 290, 151, 21))
        self.txt1_8.setStyleSheet("")
        self.txt1_8.setObjectName("txt1_8")
        self.txt1_13 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_13.setGeometry(QtCore.QRect(10, 320, 151, 21))
        self.txt1_13.setStyleSheet("")
        self.txt1_13.setObjectName("txt1_13")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(10, 340, 171, 16))
        self.line_9.setStyleSheet("")
        self.line_9.setLineWidth(3)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(10, 370, 171, 16))
        self.line_10.setStyleSheet("")
        self.line_10.setLineWidth(3)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.txt1_14 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_14.setGeometry(QtCore.QRect(10, 380, 171, 21))
        self.txt1_14.setStyleSheet("")
        self.txt1_14.setObjectName("txt1_14")
        self.txt1_16 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_16.setGeometry(QtCore.QRect(10, 350, 151, 21))
        self.txt1_16.setStyleSheet("")
        self.txt1_16.setObjectName("txt1_16")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(10, 310, 171, 8))
        self.line_16.setStyleSheet("")
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(10, 400, 171, 16))
        self.line_18.setStyleSheet("")
        self.line_18.setLineWidth(3)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(10, 430, 171, 16))
        self.line_13.setStyleSheet("")
        self.line_13.setLineWidth(3)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(10, 460, 171, 16))
        self.line_14.setStyleSheet("")
        self.line_14.setLineWidth(3)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.txt1_15 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_15.setGeometry(QtCore.QRect(10, 470, 171, 21))
        self.txt1_15.setStyleSheet("")
        self.txt1_15.setObjectName("txt1_15")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(10, 490, 171, 16))
        self.line_19.setStyleSheet("")
        self.line_19.setLineWidth(3)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.txt1_17 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_17.setGeometry(QtCore.QRect(10, 440, 151, 21))
        self.txt1_17.setStyleSheet("")
        self.txt1_17.setObjectName("txt1_17")
        self.txt1_18 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_18.setGeometry(QtCore.QRect(10, 410, 151, 21))
        self.txt1_18.setStyleSheet("")
        self.txt1_18.setObjectName("txt1_18")
        self.txt1_19 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_19.setGeometry(QtCore.QRect(10, 500, 171, 21))
        self.txt1_19.setStyleSheet("")
        self.txt1_19.setObjectName("txt1_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(10, 520, 171, 16))
        self.line_20.setStyleSheet("")
        self.line_20.setLineWidth(3)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.txt1_20 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_20.setGeometry(QtCore.QRect(10, 530, 181, 21))
        self.txt1_20.setStyleSheet("")
        self.txt1_20.setObjectName("txt1_20")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(10, 580, 171, 16))
        self.line_15.setStyleSheet("")
        self.line_15.setLineWidth(3)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(10, 550, 171, 16))
        self.line_17.setStyleSheet("")
        self.line_17.setLineWidth(3)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.txt1_22 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_22.setGeometry(QtCore.QRect(10, 560, 171, 21))
        self.txt1_22.setStyleSheet("")
        self.txt1_22.setObjectName("txt1_22")
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(10, 610, 171, 16))
        self.line_21.setStyleSheet("")
        self.line_21.setLineWidth(3)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.txt1_21 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_21.setGeometry(QtCore.QRect(10, 620, 181, 21))
        self.txt1_21.setStyleSheet("")
        self.txt1_21.setObjectName("txt1_21")
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(10, 640, 171, 16))
        self.line_22.setStyleSheet("")
        self.line_22.setLineWidth(3)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.txt1_23 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_23.setGeometry(QtCore.QRect(10, 590, 171, 21))
        self.txt1_23.setStyleSheet("")
        self.txt1_23.setObjectName("txt1_23")
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(10, 670, 171, 16))
        self.line_23.setStyleSheet("")
        self.line_23.setLineWidth(3)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.txt1_24 = QtWidgets.QLabel(self.centralwidget)
        self.txt1_24.setGeometry(QtCore.QRect(10, 650, 181, 21))
        self.txt1_24.setStyleSheet("")
        self.txt1_24.setObjectName("txt1_24")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 640, 61, 61))
        self.pushButton_2.clicked.connect(lambda e: webbrowser.open('https://theworkerthread.com/tool/no-control'))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: #0d6efd;\n"
"border-color: #0d6efd;\n"
"color: #fff;\n"
"border-radius: 30px;\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        return self.pushButton

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">2: </span><span style=\" font-size:11pt;\">{to_change[2].upper()}</span></p></body></html>"))
        self.LT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">1: </span><span style=\" font-size:11pt;\">{to_change[1].upper()}</span></p></body></html>"))
        self.RT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">3: </span><span style=\" font-size:11pt;\">{to_change[3].upper()}</span></p></body></html>"))
        self.RB.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">4: </span><span style=\" font-size:11pt;\">{to_change[4].upper()}</span></p></body></html>"))
        self.LB_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">11: </span><span style=\" font-size:10pt;\">{to_change[11].upper()}</span></p></body></html>"))
        self.LB_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">10: </span><span style=\" font-size:10pt;\">{to_change[10].upper()}</span></p></body></html>"))
        self.LB_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">12: </span><span style=\" font-size:10pt;\">{to_change[12].upper()}</span></p></body></html>"))
        self.LB_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">9: </span><span style=\" font-size:10pt;\">{to_change[9].upper()}</span></p></body></html>"))
        self.RbmU.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">5: </span><span style=\" font-size:10pt;\">{to_change[5].upper()}</span></p></body></html>"))
        self.RbmR.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">6: </span><span style=\" font-size:10pt;\">{to_change[6].upper()}</span></p></body></html>"))
        self.RbmL.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">8: </span><span style=\" font-size:10pt;\">{to_change[8].upper()}</span></p></body></html>"))
        self.RbmD.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">7: </span><span style=\" font-size:10pt;\">{to_change[7].upper()}</span></p></body></html>"))
        self.LbmU.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">17: </span><span style=\" font-size:10pt;\">{to_change[17].upper()}</span></p></body></html>"))
        self.LbmR.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">18: </span><span style=\" font-size:10pt;\">{to_change[18].upper()}</span></p></body></html>"))
        self.Xk.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">13: </span><span style=\" font-size:10pt;\">{to_change[13].upper()}</span></p></body></html>"))
        self.Yk.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">14: </span><span style=\" font-size:10pt;\">{to_change[14].upper()}</span></p></body></html>"))
        self.Bk.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">15: </span><span style=\" font-size:10pt;\">{to_change[15].upper()}</span></p></body></html>"))
        self.Ak.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">16: </span><span style=\" font-size:10pt;\">{to_change[16].upper()}</span></p></body></html>"))
        self.LbmD.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">19: </span><span style=\" font-size:10pt;\">{to_change[19].upper()}</span></p></body></html>"))
        self.LbmL.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">20: </span><span style=\" font-size:10pt;\">{to_change[20].upper()}</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "STOP (F6)"))
        self.RbmU_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:17pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">21: </span><span style=\" font-size:10pt;\">{to_change[21].upper()}</span></p></body></html>"))
        self.txt1_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">1: Left Trigger</span></p></body></html>"))
        self.txt1_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">2: Left Shoulder</span></p></body></html>"))
        self.txt1_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">3: Right Trigger</span></p></body></html>"))
        self.txt1_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">4: Right Shoulder</span></p></body></html>"))
        self.txt1_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">5: Left Stick Up</span></p></body></html>"))
        self.txt1_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">6: Left Stick Right</span></p></body></html>"))
        self.txt1_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">7: Left Stick Down</span></p></body></html>"))
        self.txt1_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">8: Left Stick Left</span></p></body></html>"))
        self.txt1_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">9: Pad Up</span></p></body></html>"))
        self.txt1_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">10: Pad Right</span></p></body></html>"))
        self.txt1_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">11: Pad Down</span></p></body></html>"))
        self.txt1_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">13: X</span></p></body></html>"))
        self.txt1_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">12: Pad Left</span></p></body></html>"))
        self.txt1_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">16: A</span></p></body></html>"))
        self.txt1_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">15: B</span></p></body></html>"))
        self.txt1_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">14: Y</span></p></body></html>"))
        self.txt1_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">17: Right Stick Up</span></p></body></html>"))
        self.txt1_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">18: Right Stick Right</span></p></body></html>"))
        self.txt1_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">19: Right Stick Down</span></p></body></html>"))
        self.txt1_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">21: Start</span></p></body></html>"))
        self.txt1_23.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">20: Right Stick Left</span></p></body></html>"))
        self.txt1_24.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">F6: Block Keyboard</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", "?"))
        MainWindow.setWindowTitle("NoControl")
